<?php
/**
 * ConnPoolConfTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenEuropa\SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenEuropa\SyncopePhpClient\Model;

use \ArrayAccess;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * ConnPoolConfTO Class Doc Comment
 *
 * @category Class
 * @package  OpenEuropa\SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnPoolConfTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ConnPoolConfTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'maxObjects' => 'int',
        'minIdle' => 'int',
        'maxIdle' => 'int',
        'maxWait' => 'int',
        'minEvictableIdleTimeMillis' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'maxObjects' => 'int32',
        'minIdle' => 'int32',
        'maxIdle' => 'int32',
        'maxWait' => 'int64',
        'minEvictableIdleTimeMillis' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'maxObjects' => 'maxObjects',
        'minIdle' => 'minIdle',
        'maxIdle' => 'maxIdle',
        'maxWait' => 'maxWait',
        'minEvictableIdleTimeMillis' => 'minEvictableIdleTimeMillis'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'maxObjects' => 'setMaxObjects',
        'minIdle' => 'setMinIdle',
        'maxIdle' => 'setMaxIdle',
        'maxWait' => 'setMaxWait',
        'minEvictableIdleTimeMillis' => 'setMinEvictableIdleTimeMillis'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'maxObjects' => 'getMaxObjects',
        'minIdle' => 'getMinIdle',
        'maxIdle' => 'getMaxIdle',
        'maxWait' => 'getMaxWait',
        'minEvictableIdleTimeMillis' => 'getMinEvictableIdleTimeMillis'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['maxObjects'] = isset($data['maxObjects']) ? $data['maxObjects'] : null;
        $this->container['minIdle'] = isset($data['minIdle']) ? $data['minIdle'] : null;
        $this->container['maxIdle'] = isset($data['maxIdle']) ? $data['maxIdle'] : null;
        $this->container['maxWait'] = isset($data['maxWait']) ? $data['maxWait'] : null;
        $this->container['minEvictableIdleTimeMillis'] = isset($data['minEvictableIdleTimeMillis']) ? $data['minEvictableIdleTimeMillis'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets maxObjects
     *
     * @return int|null
     */
    public function getMaxObjects()
    {
        return $this->container['maxObjects'];
    }

    /**
     * Sets maxObjects
     *
     * @param int|null $maxObjects maxObjects
     *
     * @return $this
     */
    public function setMaxObjects($maxObjects)
    {
        $this->container['maxObjects'] = $maxObjects;

        return $this;
    }

    /**
     * Gets minIdle
     *
     * @return int|null
     */
    public function getMinIdle()
    {
        return $this->container['minIdle'];
    }

    /**
     * Sets minIdle
     *
     * @param int|null $minIdle minIdle
     *
     * @return $this
     */
    public function setMinIdle($minIdle)
    {
        $this->container['minIdle'] = $minIdle;

        return $this;
    }

    /**
     * Gets maxIdle
     *
     * @return int|null
     */
    public function getMaxIdle()
    {
        return $this->container['maxIdle'];
    }

    /**
     * Sets maxIdle
     *
     * @param int|null $maxIdle maxIdle
     *
     * @return $this
     */
    public function setMaxIdle($maxIdle)
    {
        $this->container['maxIdle'] = $maxIdle;

        return $this;
    }

    /**
     * Gets maxWait
     *
     * @return int|null
     */
    public function getMaxWait()
    {
        return $this->container['maxWait'];
    }

    /**
     * Sets maxWait
     *
     * @param int|null $maxWait maxWait
     *
     * @return $this
     */
    public function setMaxWait($maxWait)
    {
        $this->container['maxWait'] = $maxWait;

        return $this;
    }

    /**
     * Gets minEvictableIdleTimeMillis
     *
     * @return int|null
     */
    public function getMinEvictableIdleTimeMillis()
    {
        return $this->container['minEvictableIdleTimeMillis'];
    }

    /**
     * Sets minEvictableIdleTimeMillis
     *
     * @param int|null $minEvictableIdleTimeMillis minEvictableIdleTimeMillis
     *
     * @return $this
     */
    public function setMinEvictableIdleTimeMillis($minEvictableIdleTimeMillis)
    {
        $this->container['minEvictableIdleTimeMillis'] = $minEvictableIdleTimeMillis;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


