<?php
/**
 * SCIMConf
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenEuropa\SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenEuropa\SyncopePhpClient\Model;

use \ArrayAccess;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * SCIMConf Class Doc Comment
 *
 * @category Class
 * @package  OpenEuropa\SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SCIMConf implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SCIMConf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'generalConf' => '\OpenEuropa\SyncopePhpClient\Model\SCIMGeneralConf',
        'userConf' => '\OpenEuropa\SyncopePhpClient\Model\SCIMUserConf',
        'enterpriseUserConf' => '\OpenEuropa\SyncopePhpClient\Model\SCIMEnterpriseUserConf'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'generalConf' => null,
        'userConf' => null,
        'enterpriseUserConf' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'generalConf' => 'generalConf',
        'userConf' => 'userConf',
        'enterpriseUserConf' => 'enterpriseUserConf'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'generalConf' => 'setGeneralConf',
        'userConf' => 'setUserConf',
        'enterpriseUserConf' => 'setEnterpriseUserConf'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'generalConf' => 'getGeneralConf',
        'userConf' => 'getUserConf',
        'enterpriseUserConf' => 'getEnterpriseUserConf'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['generalConf'] = isset($data['generalConf']) ? $data['generalConf'] : null;
        $this->container['userConf'] = isset($data['userConf']) ? $data['userConf'] : null;
        $this->container['enterpriseUserConf'] = isset($data['enterpriseUserConf']) ? $data['enterpriseUserConf'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets generalConf
     *
     * @return \OpenEuropa\SyncopePhpClient\Model\SCIMGeneralConf|null
     */
    public function getGeneralConf()
    {
        return $this->container['generalConf'];
    }

    /**
     * Sets generalConf
     *
     * @param \OpenEuropa\SyncopePhpClient\Model\SCIMGeneralConf|null $generalConf generalConf
     *
     * @return $this
     */
    public function setGeneralConf($generalConf)
    {
        $this->container['generalConf'] = $generalConf;

        return $this;
    }

    /**
     * Gets userConf
     *
     * @return \OpenEuropa\SyncopePhpClient\Model\SCIMUserConf|null
     */
    public function getUserConf()
    {
        return $this->container['userConf'];
    }

    /**
     * Sets userConf
     *
     * @param \OpenEuropa\SyncopePhpClient\Model\SCIMUserConf|null $userConf userConf
     *
     * @return $this
     */
    public function setUserConf($userConf)
    {
        $this->container['userConf'] = $userConf;

        return $this;
    }

    /**
     * Gets enterpriseUserConf
     *
     * @return \OpenEuropa\SyncopePhpClient\Model\SCIMEnterpriseUserConf|null
     */
    public function getEnterpriseUserConf()
    {
        return $this->container['enterpriseUserConf'];
    }

    /**
     * Sets enterpriseUserConf
     *
     * @param \OpenEuropa\SyncopePhpClient\Model\SCIMEnterpriseUserConf|null $enterpriseUserConf enterpriseUserConf
     *
     * @return $this
     */
    public function setEnterpriseUserConf($enterpriseUserConf)
    {
        $this->container['enterpriseUserConf'] = $enterpriseUserConf;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


