<?php
/**
 * AnyObjectsApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * AnyObjectsApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class AnyObjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for associateAnyObject.
     *
     * Executes resource-related operations on given entity..
     *
     */
    public function testAssociateAnyObject()  {
    }

    /**
     * Test case for createAnyObject.
     *
     * Creates a new any object..
     *
     */
    public function testCreateAnyObject()  {
    }

    /**
     * Test case for deassociateAnyObject.
     *
     * Executes resource-related operations on given entity..
     *
     */
    public function testDeassociateAnyObject()  {
    }

    /**
     * Test case for deleteAnyObject.
     *
     * Deletes any object matching provided key..
     *
     */
    public function testDeleteAnyObject()  {
    }

    /**
     * Test case for deleteAnyObjectAttribute.
     *
     * Deletes the attribute, owned by the given any object, for the given schema type and schema..
     *
     */
    public function testDeleteAnyObjectAttribute()  {
    }

    /**
     * Test case for readAnyObject.
     *
     * Reads the any object matching the provided key..
     *
     */
    public function testReadAnyObject()  {
    }

    /**
     * Test case for readAnyObjectAttribute.
     *
     * Reads the attribute, owned by the given any object, for the given schema type and schema.   Note that for the UserService, GroupService and AnyObjectService subclasses, if the key parameter  looks like a UUID then it is interpreted as as key, otherwise as a (user)name..
     *
     */
    public function testReadAnyObjectAttribute()  {
    }

    /**
     * Test case for readAnyObjectAttributeForSchema.
     *
     * Reads the list of attributes owned by the given any object for the given schema type.   Note that for the UserService, GroupService and AnyObjectService subclasses, if the key parameter  looks like a UUID then it is interpreted as as key, otherwise as a (user)name..
     *
     */
    public function testReadAnyObjectAttributeForSchema()  {
    }

    /**
     * Test case for searchAnyObject.
     *
     * Returns a paged list of any objects matching the given query..
     *
     */
    public function testSearchAnyObject()  {
    }

    /**
     * Test case for updateAnyObject.
     *
     * Updates any object matching the provided key..
     *
     */
    public function testUpdateAnyObject()  {
    }

    /**
     * Test case for updateAnyObjectAttribute.
     *
     * Adds or replaces the attribute, owned by the given any object, for the given schema type and schema..
     *
     */
    public function testUpdateAnyObjectAttribute()  {
    }

    /**
     * Test case for updateAnyObjectPartial.
     *
     * Updates any object matching the provided key..
     *
     */
    public function testUpdateAnyObjectPartial()  {
    }
}
