<?php
/**
 * AnyTypesApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * AnyTypesApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class AnyTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for createAnyType.
     *
     * Creates a new anyType..
     *
     */
    public function testCreateAnyType()  {
    }

    /**
     * Test case for deleteAnyType.
     *
     * Deletes the anyType matching the provided key..
     *
     */
    public function testDeleteAnyType()  {
    }

    /**
     * Test case for listAnyType.
     *
     * Returns a list of all anyTypes..
     *
     */
    public function testListAnyType()  {
    }

    /**
     * Test case for readAnyType.
     *
     * Returns anyType with matching key..
     *
     */
    public function testReadAnyType()  {
    }

    /**
     * Test case for updateAnyType.
     *
     * Updates the anyType matching the provided key..
     *
     */
    public function testUpdateAnyType()  {
    }
}
