<?php
/**
 * AnyTypeClassesApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * AnyTypeClassesApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class AnyTypeClassesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for createAnyTypeClass.
     *
     * Creates a new anyTypeClass..
     *
     */
    public function testCreateAnyTypeClass()  {
    }

    /**
     * Test case for deleteAnyTypeClass.
     *
     * Deletes the anyTypeClass matching the provided key..
     *
     */
    public function testDeleteAnyTypeClass()  {
    }

    /**
     * Test case for listAnyTypeClass.
     *
     * Returns a list of all anyTypeClasss..
     *
     */
    public function testListAnyTypeClass()  {
    }

    /**
     * Test case for readAnyTypeClass.
     *
     * Returns anyTypeClass with matching key..
     *
     */
    public function testReadAnyTypeClass()  {
    }

    /**
     * Test case for updateAnyTypeClass.
     *
     * Updates the anyTypeClass matching the provided key..
     *
     */
    public function testUpdateAnyTypeClass()  {
    }
}
