<?php
/**
 * CamelRoutesApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * CamelRoutesApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class CamelRoutesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for list4.
     *
     * List all routes for the given any type kind..
     *
     */
    public function testList4()  {
    }

    /**
     * Test case for metrics.
     *
     * Provides Camel metrics..
     *
     */
    public function testMetrics()  {
    }

    /**
     * Test case for read6.
     *
     * Read the route with the given key..
     *
     */
    public function testRead6()  {
    }

    /**
     * Test case for restartContext.
     *
     * Restart the underlying Apache Camel context..
     *
     */
    public function testRestartContext()  {
    }

    /**
     * Test case for update.
     *
     * Update the given route..
     *
     */
    public function testUpdate()  {
    }
}
