<?php
/**
 * ConnectorsApiTest.
 * PHP version 5
 *
 * @category Class
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenEuropa\SyncopePhpClient\Test\Api;

use \OpenEuropa\SyncopePhpClient\Configuration;
use \OpenEuropa\SyncopePhpClient\ApiException;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * ConnectorsApiTest Class Doc Comment.
 *
 * @category Class.
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class ConnectorsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for buildObjectClassInfo.
     *
     * Builds the list of ConnId object classes information for the connector bundle matching the given connector  instance key, with the provided configuration..
     *
     */
    public function testBuildObjectClassInfo()  {
    }

    /**
     * Test case for check.
     *
     * Checks whether the connection to resource could be established..
     *
     */
    public function testCheck()  {
    }

    /**
     * Test case for create.
     *
     * Creates a new connector instance..
     *
     */
    public function testCreate()  {
    }

    /**
     * Test case for delete1.
     *
     * Deletes the connector instance matching the provided key..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for getBundles.
     *
     * Returns available connector bundles with property keys in selected language..
     *
     */
    public function testGetBundles()  {
    }

    /**
     * Test case for list7.
     *
     * Returns a list of all connector instances with property keys in the matching language..
     *
     */
    public function testList7()  {
    }

    /**
     * Test case for read7.
     *
     * Returns connector instance with matching key..
     *
     */
    public function testRead7()  {
    }

    /**
     * Test case for readByResource.
     *
     * Returns connector instance for matching resource..
     *
     */
    public function testReadByResource()  {
    }

    /**
     * Test case for reload.
     *
     * Reload all connector bundles and instances..
     *
     */
    public function testReload()  {
    }

    /**
     * Test case for update.
     *
     * Updates the connector instance matching the provided key..
     *
     */
    public function testUpdate()  {
    }
}
