<?php
/**
 * GroupsApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for associateGroup.
     *
     * Executes resource-related operations on given entity..
     *
     */
    public function testAssociateGroup()  {
    }

    /**
     * Test case for createGroup.
     *
     * Creates a new group..
     *
     */
    public function testCreateGroup()  {
    }

    /**
     * Test case for deassociateGroup.
     *
     * Executes resource-related operations on given entity..
     *
     */
    public function testDeassociateGroup()  {
    }

    /**
     * Test case for deleteGroup.
     *
     * Deletes any object matching provided key..
     *
     */
    public function testDeleteGroup()  {
    }

    /**
     * Test case for deleteGroupAttribute.
     *
     * Deletes the attribute, owned by the given any object, for the given schema type and schema..
     *
     */
    public function testDeleteGroupAttribute()  {
    }

    /**
     * Test case for own.
     *
     * This method allows a user to read his own groups..
     *
     */
    public function testOwn()  {
    }

    /**
     * Test case for provisionMembers.
     *
     * (De)provision all members of the given group from / onto all the resources associated to it..
     *
     */
    public function testProvisionMembers()  {
    }

    /**
     * Test case for readGroup.
     *
     * Reads the any object matching the provided key..
     *
     */
    public function testReadGroup()  {
    }

    /**
     * Test case for readGroupAttribute.
     *
     * Reads the attribute, owned by the given any object, for the given schema type and schema.   Note that for the UserService, GroupService and AnyObjectService subclasses, if the key parameter  looks like a UUID then it is interpreted as as key, otherwise as a (user)name..
     *
     */
    public function testReadGroupAttribute()  {
    }

    /**
     * Test case for readGroupAttributeForSchema.
     *
     * Reads the list of attributes owned by the given any object for the given schema type.   Note that for the UserService, GroupService and AnyObjectService subclasses, if the key parameter  looks like a UUID then it is interpreted as as key, otherwise as a (user)name..
     *
     */
    public function testReadGroupAttributeForSchema()  {
    }

    /**
     * Test case for searchGroup.
     *
     * Returns a paged list of any objects matching the given query..
     *
     */
    public function testSearchGroup()  {
    }

    /**
     * Test case for updateGroup.
     *
     * Updates group matching the provided key..
     *
     */
    public function testUpdateGroup()  {
    }

    /**
     * Test case for updateGroupAttribute.
     *
     * Adds or replaces the attribute, owned by the given any object, for the given schema type and schema..
     *
     */
    public function testUpdateGroupAttribute()  {
    }

    /**
     * Test case for updateGroup_0.
     *
     * Updates group matching the provided key..
     *
     */
    public function testUpdateGroup0()  {
    }
}
