<?php
/**
 * ImplementationsApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * ImplementationsApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class ImplementationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for create.
     *
     * Creates a new implementation..
     *
     */
    public function testCreate()  {
    }

    /**
     * Test case for delete1.
     *
     * Deletes the implementation matching the given key and type..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for list10.
     *
     * Returns a list of all implementations of the given type..
     *
     */
    public function testList10()  {
    }

    /**
     * Test case for read13.
     *
     * Returns implementation with matching type and key..
     *
     */
    public function testRead13()  {
    }

    /**
     * Test case for update.
     *
     * Updates an existing implementation..
     *
     */
    public function testUpdate()  {
    }
}
