<?php
/**
 * LoggersApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * LoggersApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class LoggersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for delete1.
     *
     * Deletes the logger with matching name..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for events.
     *
     * Returns the list of all managed events in audit..
     *
     */
    public function testEvents()  {
    }

    /**
     * Test case for getLastLogStatements.
     *
     * Return the last log statements available in the provided memory appender..
     *
     */
    public function testGetLastLogStatements()  {
    }

    /**
     * Test case for list11.
     *
     * Returns a list of loggers with matching type..
     *
     */
    public function testList11()  {
    }

    /**
     * Test case for memoryAppenders.
     *
     * Returns the list of memory appenders available in the current logging configuration..
     *
     */
    public function testMemoryAppenders()  {
    }

    /**
     * Test case for read14.
     *
     * Returns logger with matching type and name..
     *
     */
    public function testRead14()  {
    }

    /**
     * Test case for update.
     *
     * Creates or updates (if existing) the logger with matching name..
     *
     */
    public function testUpdate()  {
    }
}
