<?php
/**
 * NotificationsApiTest.
 * PHP version 5
 *
 * @category Class
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenEuropa\SyncopePhpClient\Test\Api;

use \OpenEuropa\SyncopePhpClient\Configuration;
use \OpenEuropa\SyncopePhpClient\ApiException;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * NotificationsApiTest Class Doc Comment.
 *
 * @category Class.
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class NotificationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for actionJob.
     *
     * Executes an action on the notification job..
     *
     */
    public function testActionJob()  {
    }

    /**
     * Test case for create.
     *
     * Creates a new notification..
     *
     */
    public function testCreate()  {
    }

    /**
     * Test case for delete1.
     *
     * Deletes the notification matching the given key..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for getJob.
     *
     * Returns details about notification job..
     *
     */
    public function testGetJob()  {
    }

    /**
     * Test case for list13.
     *
     * Returns a list of all notifications..
     *
     */
    public function testList13()  {
    }

    /**
     * Test case for read16.
     *
     * Returns notification with matching key..
     *
     */
    public function testRead16()  {
    }

    /**
     * Test case for update1.
     *
     * Updates the notification matching the given key..
     *
     */
    public function testUpdate1()  {
    }
}
