<?php
/**
 * OIDCProvidersApiTest.
 * PHP version 5
 *
 * @category Class
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenEuropa\SyncopePhpClient\Test\Api;

use \OpenEuropa\SyncopePhpClient\Configuration;
use \OpenEuropa\SyncopePhpClient\ApiException;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * OIDCProvidersApiTest Class Doc Comment.
 *
 * @category Class.
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class OIDCProvidersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for create.
     *
     * Creates a new OIDC Provider..
     *
     */
    public function testCreate()  {
    }

    /**
     * Test case for createFromDiscovery.
     *
     * Creates a new OIDC Provider by using its Discovery Document..
     *
     */
    public function testCreateFromDiscovery()  {
    }

    /**
     * Test case for delete1.
     *
     * Deletes the OIDC Provider with matching key..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for getActionsClasses.
     *
     * Returns the list of available OIDCProviderActions implementations..
     *
     */
    public function testGetActionsClasses()  {
    }

    /**
     * Test case for list14.
     *
     * Returns a list of all defined OIDC Providers..
     *
     */
    public function testList14()  {
    }

    /**
     * Test case for read17.
     *
     * Returns the OIDC Provider with matching key, if available..
     *
     */
    public function testRead17()  {
    }

    /**
     * Test case for update1.
     *
     * Updates the OIDC Provider with matching key..
     *
     */
    public function testUpdate1()  {
    }
}
