<?php
/**
 * PoliciesApiTest.
 * PHP version 5
 *
 * @category Class
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenEuropa\SyncopePhpClient\Test\Api;

use \OpenEuropa\SyncopePhpClient\Configuration;
use \OpenEuropa\SyncopePhpClient\ApiException;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * PoliciesApiTest Class Doc Comment.
 *
 * @category Class.
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class PoliciesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for create.
     *
     * Create a new policy..
     *
     */
    public function testCreate()  {
    }

    /**
     * Test case for delete1.
     *
     * Delete policy matching the given key..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for list15.
     *
     * Returns a list of policies of the matching type..
     *
     */
    public function testList15()  {
    }

    /**
     * Test case for read18.
     *
     * Returns the policy matching the given key..
     *
     */
    public function testRead18()  {
    }

    /**
     * Test case for update1.
     *
     * Updates policy matching the given key..
     *
     */
    public function testUpdate1()  {
    }
}
