<?php
/**
 * ResourcesApiTest.
 * PHP version 5
 *
 * @category Class
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenEuropa\SyncopePhpClient\Test\Api;

use \OpenEuropa\SyncopePhpClient\Configuration;
use \OpenEuropa\SyncopePhpClient\ApiException;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * ResourcesApiTest Class Doc Comment.
 *
 * @category Class.
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class ResourcesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for check1.
     *
     * Checks whether the connection to resource could be established..
     *
     */
    public function testCheck1()  {
    }

    /**
     * Test case for create1.
     *
     * Creates a new resource..
     *
     */
    public function testCreate1()  {
    }

    /**
     * Test case for delete1.
     *
     * Deletes the resource matching the given name..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for list23.
     *
     * Returns a list of all resources..
     *
     */
    public function testList23()  {
    }

    /**
     * Test case for listConnObjects.
     *
     * Returns a paged list of connector objects from external resource, for the given type, matching  page/size conditions..
     *
     */
    public function testListConnObjects()  {
    }

    /**
     * Test case for read23.
     *
     * Returns the resource with matching name..
     *
     */
    public function testRead23()  {
    }

    /**
     * Test case for readConnObject.
     *
     * Returns connector object from the external resource, for the given type and key..
     *
     */
    public function testReadConnObject()  {
    }

    /**
     * Test case for removeSyncToken.
     *
     * Removes the sync token value associated to the given any type from the given resource..
     *
     */
    public function testRemoveSyncToken()  {
    }

    /**
     * Test case for setLatestSyncToken.
     *
     * Queries the connector underlying the given resource for the latest sync token value associated to the given any  type and stores the value internally, for later usage..
     *
     */
    public function testSetLatestSyncToken()  {
    }

    /**
     * Test case for update1.
     *
     * Updates the resource matching the given name..
     *
     */
    public function testUpdate1()  {
    }
}
