<?php
/**
 * SAML2SPApiTest.
 * PHP version 5
 *
 * @category Class
 * @package  SyncopePhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SyncopePhpClient;

use \SyncopePhpClient\Configuration;
use \SyncopePhpClient\ApiException;
use \SyncopePhpClient\ObjectSerializer;

/**
 * SAML2SPApiTest Class Doc Comment.
 *
 * @category Class.
 * @package SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class SAML2SPApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for createLoginRequest1.
     *
     * Generates SAML 2.0 authentication request for the IdP matching the provided entity ID..
     *
     */
    public function testCreateLoginRequest1()  {
    }

    /**
     * Test case for createLogoutRequest1.
     *
     * Generates SAML 2.0 logout request for the IdP matching the requesting access token..
     *
     */
    public function testCreateLogoutRequest1()  {
    }

    /**
     * Test case for getMetadata.
     *
     * Returns the XML metadata for the provided SAML 2.0 Service Provider..
     *
     */
    public function testGetMetadata()  {
    }

    /**
     * Test case for validateLoginResponse.
     *
     * Validates the received SAML 2.0 authentication response and creates JWT for the matching user, if found..
     *
     */
    public function testValidateLoginResponse()  {
    }

    /**
     * Test case for validateLogoutResponse.
     *
     * Validates the received SAML 2.0 logout response..
     *
     */
    public function testValidateLogoutResponse()  {
    }
}
