<?php
/**
 * SAML2IdPApiTest.
 * PHP version 5
 *
 * @category Class
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenEuropa\SyncopePhpClient\Test\Api;

use \OpenEuropa\SyncopePhpClient\Configuration;
use \OpenEuropa\SyncopePhpClient\ApiException;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * SAML2IdPApiTest Class Doc Comment.
 *
 * @category Class.
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class SAML2IdPApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for delete1.
     *
     * Deletes the SAML 2.0 Identity Provider with matching entityID..
     *
     */
    public function testDelete1()  {
    }

    /**
     * Test case for getActionsClasses1.
     *
     * Returns the list of available SAML2IdPActions implementations..
     *
     */
    public function testGetActionsClasses1()  {
    }

    /**
     * Test case for importFromMetadata.
     *
     * Imports the SAML 2.0 Identity Provider definitions available in the provided XML metadata..
     *
     */
    public function testImportFromMetadata()  {
    }

    /**
     * Test case for list25.
     *
     * Returns a list of all defined SAML 2.0 Identity Providers..
     *
     */
    public function testList25()  {
    }

    /**
     * Test case for read25.
     *
     * Returns the SAML 2.0 Identity Provider with matching entityID, if available..
     *
     */
    public function testRead25()  {
    }

    /**
     * Test case for update1.
     *
     * Updates the SAML 2.0 Identity Provider with matching entityID..
     *
     */
    public function testUpdate1()  {
    }
}
