<?php
/**
 * SyncopeApiTest.
 * PHP version 5
 *
 * @category Class
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */

/**
 * Apache Syncope
 *
 * Apache Syncope 2.1.2-SNAPSHOT
 *
 * OpenAPI spec version: 2.1.2-SNAPSHOT
 * Contact: dev@syncope.apache.org
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenEuropa\SyncopePhpClient\Test\Api;

use \OpenEuropa\SyncopePhpClient\Configuration;
use \OpenEuropa\SyncopePhpClient\ApiException;
use \OpenEuropa\SyncopePhpClient\ObjectSerializer;

/**
 * SyncopeApiTest Class Doc Comment.
 *
 * @category Class.
 * @package OpenEuropa\SyncopePhpClient
 * @author OpenAPI Generator team
 * @link https://openapi-generator.tech
 */
class SyncopeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()  {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()  {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()  {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()  {
    }

    /**
     * Test case for batch.
     *
     * Gets batch results, in case asynchronous was requested..
     *
     */
    public function testBatch()  {
    }

    /**
     * Test case for batch1.
     *
     * Requests for batch execution..
     *
     */
    public function testBatch1()  {
    }

    /**
     * Test case for numbers.
     *
     * Provides some numbers about the managed entities (users, groups, any objects...)..
     *
     */
    public function testNumbers()  {
    }

    /**
     * Test case for platform.
     *
     * Provides information summary about platform configuration (workflow adapters, provisioning managers, validators,  actions, correlation rules, reportlets, ...)..
     *
     */
    public function testPlatform()  {
    }

    /**
     * Test case for readUserTypeExtension.
     *
     * Extracts User type extension information, for the provided group..
     *
     */
    public function testReadUserTypeExtension()  {
    }

    /**
     * Test case for searchAssignableGroups.
     *
     * Returns the list of Groups, according to provided paging instructions, assignable to Users and Any Objects of  the provided Realm..
     *
     */
    public function testSearchAssignableGroups()  {
    }

    /**
     * Test case for system.
     *
     * Provides information about the underlying system (Operating System, CPU / memory usage, ...)..
     *
     */
    public function testSystem()  {
    }
}
